// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitOfMeasures.Infrastructure.Persistence.Contexts;

#nullable disable

namespace UnitOfMeasures.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SQLiteDataBaseContext))]
    [Migration("20220818120320_ss")]
    partial class ss
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("UnitOfMeasures.Core.Domain.Dimension.Entities.Dimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("UnitOfMeasures.Core.Domain.Unit.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConversionFactor")
                        .HasColumnType("REAL");

                    b.Property<Guid>("DimensionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormulaFromBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormulaToBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("UnitOfMeasures.Core.Domain.Unit.Entities.Unit", b =>
                {
                    b.HasOne("UnitOfMeasures.Core.Domain.Dimension.Entities.Dimension", "Dimension")
                        .WithMany("Units")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimension");
                });

            modelBuilder.Entity("UnitOfMeasures.Core.Domain.Dimension.Entities.Dimension", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
